public enum AppState
{
    FRESH = 0,
    FIRST_JOURNAL_ENTRY = 1,
    FIRST_MINDFULNESS = 2,
    EXERCISE = 3,

    SECOND_MINDFULNESS = 4,
    SECOND_JOURNAL = 5,
    ALL_DONE = 6,

    REST_FIRST_JOURNAL_ENTRY = 11,
    REST_FIRST_MINDFULNESS = 12,

    REST_SECOND_MINDFULNESS = 14,
    REST_SECOND_JOURNAL = 15,
    REST_ALL_DONE = 16,

}